### ISSUE TITLE
Tried to install iPhone 6s 10.3.1

### ISSUE THREAD

**Issue by ollimyers1** [thisiswisy/v0rtex-injector#1]
Installed IPA but app said my device was incompatible even though I have an iPhone 6s on 10.3.1

**Comment by NickSB2013** [comment]
That's because the offsets are wrong according to this: https://github.com/arx8x/v0rtex_offsets/blob/master/koffset_n71_1032

**Comment by NickSB2013** [comment]
From the two offset sources (one in the last post) and this below: neither match the ones in the IPA/project.

iPhone 6s iOS 10.3.1 Offsets

#define OFFSET_ZONE_MAP                             0xfffffff007548478 
#define OFFSET_KERNEL_MAP                           0xfffffff0075a4050
#define OFFSET_KERNEL_TASK                         0xfffffff0075a4048
#define OFFSET_REALHOST                             0xfffffff00752aba0
#define OFFSET_BZERO                                0xfffffff007081f80
#define OFFSET_BCOPY                                0xfffffff007081dc0
#define OFFSET_COPYIN                               0xfffffff007180720
#define OFFSET_COPYOUT                              0xfffffff007180914
#define OFFSET_IPC_PORT_ALLOC_SPECIAL               0xfffffff007099efc 
#define OFFSET_IPC_KOBJECT_SET                     0xfffffff0070ad154 
#define OFFSET_IPC_PORT_MAKE_SEND                 0xfffffff007099a20 
#define OFFSET_IOSURFACEROOTUSERCLIENT_VTAB         0xfffffff006e7c9f8
#define OFFSET_ROP_ADD_X0_X0_0x10                   0xfffffff006465174

**Comment by jakeajames** [comment]
I forgot to add offsets to the ipa

**Comment by EPiCxRIOTZZ** [comment]
i keep getting the "system isnt available in ios" error and it wont build, any chance of a compiled version?

**Comment by NickSB2013** [comment]
Yeah, I keep getting that 'not available in ios' error too when trying to archive in Xcode... how the hell do we get past this error anyone?
