### ISSUE TITLE
input link to deb to install？

### ISSUE THREAD

**Issue by yycmd** [thisiswisy/v0rtex-injector#10]
![qq 20171225162445](https://user-images.githubusercontent.com/17695132/34336364-6c835f56-e991-11e7-8d17-1ff64624b084.png)

**Comment by ghost** [comment]
Pretty self explanatory. Insert a link to a deb file for a tweak you want. You can find links to deb files here: https://tweakupdates.com/

For example the deb file for Cylinder: http://apt.thebigboss.org/repofiles/cydia/debs2.0/cylinder_1.0.6.deb

**Comment by yycmd** [comment]
@notexe Thank you very much.

**Comment by ghost** [comment]
No problem, you should probably close this issue now :P

**Comment by leart78** [comment]
okay for free debs, but how about for purchased ones???
