### ISSUE TITLE
iphone 6s 10.3.3 Offsets 

### ISSUE THREAD

**Issue by xxxsapnasxxx** [thisiswisy/v0rtex-injector#17]
if ([ver isEqual: @"Version 10.3.3 (Build 14G60)"])
        {
            OFFSET_ZONE_MAP                            = 0xfffffff007548478;
            OFFSET_KERNEL_MAP                          = 0xfffffff0075a4050;
            OFFSET_KERNEL_TASK                         = 0xfffffff0075a4048;
            OFFSET_REALHOST                            = 0xfffffff00752aba0;
            OFFSET_BZERO                               = 0xfffffff007081f80;
            OFFSET_BCOPY                               = 0xfffffff007081dc0;
            OFFSET_COPYIN                              = 0xfffffff0071803a0;
            OFFSET_COPYOUT                             = 0xfffffff007180594;
            OFFSET_CHGPROCCNT                          = 0xfffffff007049e01;
            OFFSET_KAUTH_CRED_REF                      = 0xfffffff007367c18;
            //OFFSET_KAUTH_CRED_UNREF                    = 0xfffffff0073678f8;
            OFFSET_IPC_PORT_ALLOC_SPECIAL              = 0xfffffff007099e94;
            OFFSET_IPC_KOBJECT_SET                     = 0xfffffff0070ad16c;
            OFFSET_IPC_PORT_MAKE_SEND                  = 0xfffffff0070999b8;
            OFFSET_IOSURFACEROOTUSERCLIENT_VTAB        = 0xfffffff006e7c9f8;
            OFFSET_ROP_ADD_X0_X0_0x10                  = 0xfffffff006462174;
            OFFSET_ROP_LDR_X0_X0_0x10                  = 0xfffffff0073690d8;
            OFFSET_ROOT_MOUNT_V_NODE                   = 0xfffffff0075a40b0;
        }

**Comment by xxxsapnasxxx** [comment]
xcode 9.2   i get  3 error     
system("/usr/libexec/cydia/firmware.sh");'system' is unavailable: not available on iOS
system([firstcmd UTF8String]);system' is unavailable: not available on iOS
system([secondcmd UTF8String]); //install'system' is unavailable: not available on iOS


how can i fix ?

**Comment by thisiswisy** [comment]
look at #3
