### ISSUE TITLE
iPhone 7 10.3.2 Check Here

### ISSUE THREAD

**Issue by pir7** [thisiswisy/v0rtex-injector#21]
i got error on my iPhone 7 10.3.2 
i am not sure but here's some offsets maybe useful
=i will test this

//10.3.3
OFFSET_ZONE_MAP                             = 0xfffffff007590478;
OFFSET_KERNEL_MAP                           = 0xfffffff0075ec050;
OFFSET_KERNEL_TASK                          = 0xfffffff0075ec048;
OFFSET_REALHOST                             = 0xfffffff007572ba0;
OFFSET_BZERO                                = 0xfffffff0070c1f80;
OFFSET_BCOPY                                = 0xfffffff0070c1dc0;
OFFSET_COPYIN                               = 0xfffffff0071c5db4;
OFFSET_COPYOUT                              = 0xfffffff0071c6094;
OFFSET_IPC_PORT_ALLOC_SPECIAL               = 0xfffffff0070deff4;
OFFSET_IPC_KOBJECT_SET                      = 0xfffffff0070f22cc;
OFFSET_IPC_PORT_MAKE_SEND                   = 0xfffffff0070deb18;
OFFSET_IOSURFACEROOTUSERCLIENT_VTAB         = 0xfffffff006e49208 + 0x1030;
OFFSET_ROP_ADD_X0_X0_0x10                   = 0xfffffff0063c5398;

//10.3.2
OFFSET_ZONE_MAP                             = 0xfffffff007590478;
OFFSET_KERNEL_MAP                           = 0xfffffff0075ec050;
OFFSET_KERNEL_TASK                          = 0xfffffff0075ec048;
OFFSET_REALHOST                             = 0xfffffff007572ba0;
OFFSET_BZERO                                = 0xfffffff0070c1f80;
OFFSET_BCOPY                                = 0xfffffff0070c1dc0;
OFFSET_COPYIN                               = 0xfffffff0071c6108;
OFFSET_COPYOUT                              = 0xfffffff0071c63e8;
OFFSET_IPC_PORT_ALLOC_SPECIAL               = 0xfffffff0070deff4;
OFFSET_IPC_KOBJECT_SET                      = 0xfffffff0070f22cc;
OFFSET_IPC_PORT_MAKE_SEND                   = 0xfffffff0070deb18;
OFFSET_IOSURFACEROOTUSERCLIENT_VTAB         = 0xfffffff006e49208 + 0x1030;
OFFSET_ROP_ADD_X0_X0_0x10                   = 0xfffffff0065000a8;
 
//10.3.1
OFFSET_ZONE_MAP                             = 0xfffffff007590478;
OFFSET_KERNEL_MAP                           = 0xfffffff0075ec050;
OFFSET_KERNEL_TASK                          = 0xfffffff0075ec048;
OFFSET_REALHOST                             = 0xfffffff007572ba0;
OFFSET_BZERO                                = 0xfffffff0070c1f80;
OFFSET_BCOPY                                = 0xfffffff0070c1dc0;
OFFSET_COPYIN                               = 0xfffffff0071c6134;
OFFSET_COPYOUT                              = 0xfffffff0071c6414;
OFFSET_IPC_PORT_ALLOC_SPECIAL               = 0xfffffff0070df05c;
OFFSET_IPC_KOBJECT_SET                      = 0xfffffff0070f22b4;
OFFSET_IPC_PORT_MAKE_SEND                   = 0xfffffff0070deb80;
OFFSET_IOSURFACEROOTUSERCLIENT_VTAB         = 0xfffffff006e49208 + 0x1030;
OFFSET_ROP_ADD_X0_X0_0x10                   = 0xfffffff0064ff0a8;

**Comment by hanroid** [comment]
How do i use the offsets?

**Comment by ishu0786** [comment]
Did you use partialzip browser to find offsets
