### ISSUE TITLE
Why can not support 10.2 / 10.2.1 above ip7 / 7 +? They really need help! ! ! ! ! !

### ISSUE THREAD

**Issue by Wang0529** [thisiswisy/v0rtex-injector#24]
10.2 / 10.2.1 on 7 / 7p have a perfect cydia experience but no one to do them would rather give up he hate him ignore him really poor people were neglected forgotten be cast aside you can solve their immediate needs Help them? They are too helpless。
10.2.1/10.2 Cydia and appsync on the 7/7 + is very complete but no one is willing to do so ignore it People seem to hate 10.2 / 10.2.1 on the ip7 / 7 + prefer to ignore them do not attach importance to timely vulnerability KPP also bypassed and did not do I do not understand。
why?

**Comment by Wang0529** [comment]
Looks like you hate him?
@thisiswisy

**Comment by thisiswisy** [comment]
I haven managed to successfully get rw on 10.2.x. Closing
