### ISSUE TITLE
Activation Screen

### ISSUE THREAD

**Issue by imaqtcat** [thisiswisy/v0rtex-injector#27]
After pressing start my device(iph 7+ 10.3.1) rebooted and got into activation screen. Now everytime i reboot my device it takes me there. Also i never get it to success even though yersterday it did. I tried over 50 times today no success at all. 

edit: so it worked. cydia is now working with the latest releas b5rv2 before it used to crash. still getting into the activation screen every reboot.

edit2: everytime i run killall SpringBoard through ssh device reboots instead of respring.

**Comment by imaqtcat** [comment]
so i got it to work. cydia is now working with the latest releas b5rv2 before it used to crash. still getting into the activation screen every reboot.

**Comment by thisiswisy** [comment]
The activation screen issue is very weird, I've actually seen other people have it. I do not destroy any system files, so why would that happen? Anyway, reset all contents & settings will fix it. (Use reset jailbreak later). And I am looking into the killall issue.

**Comment by imaqtcat** [comment]
hmm ok thanks. btw now instead of activation screen i get "press home to upgrade" message at the bottom and then a white screen with the apple logo pops with a loading bar

**Comment by thisiswisy** [comment]
Fixed
