### ISSUE TITLE
activation screen I7 10.3.3 Beta 6

### ISSUE THREAD

**Issue by danielyc** [thisiswisy/v0rtex-injector#38]
still getting the activation screen with beta 6

**Comment by vincentlarkin** [comment]
Follow the instructions in the readme to fix it.

**Comment by thisiswisy** [comment]
Reset all settings, of that doesn't work reset all contents & settings. Still trying to fix the issue

**Comment by danielyc** [comment]
@VinLark i know how to fix it, I am just letting @thisiswisy know that the bug is still present. I think it has something to do with the second method of tweak activation.
