### ISSUE TITLE
It's hard to support ip7 / 7 + on 10.2.x, but please give me some hope? Really do not give up!

### ISSUE THREAD

**Issue by Wang0529** [thisiswisy/v0rtex-injector#54]
I know that you have said many times about this question, you will not support it, and you do not want to do that either. Do not give up okay?

**Comment by Wang0529** [comment]
@thisiswisy

**Comment by Wang0529** [comment]
You are a good person, try hard for us all right? Thank you.

**Comment by thisiswisy** [comment]
I will not do that. If someone will he is welcome
