### ISSUE TITLE
Cydia version .deb install on 10.3.1?

### ISSUE THREAD

**Issue by YorhaX2P** [thisiswisy/v0rtex-injector#59]
Just ask a question. But not an issue.
I'm on iPhone 5s - Global, IOS 10.3.1.

Cydia can support 10.3.1 .deb: http://apt.saurik.com/cydia/debs/cydia_1.1.30_iphoneos-arm.deb correct?
It's 16 February 2017.

**Comment by thisiswisy** [comment]
Cydia is being installed automatically. The debs option is only for tweaks
