### ISSUE TITLE
Cydia crash from latest tool

### ISSUE THREAD

**Issue by iM4CH3T3** [thisiswisy/v0rtex-injector#60]

**Comment by iM4CH3T3** [comment]
Cydia crash log 

https://www.dropbox.com/s/nddu8wef721w7cx/Datei%2001.01.18%2C%2021%2042%2045.txt?dl=0

**Comment by 211this** [comment]
Cydia crash log 
[iphone 6s 10.3.2 crash report.pdf](https://github.com/thisiswisy/v0rtex-injector/files/1596397/iphone.6s.10.3.2.crash.report.pdf)
[app.docx](https://github.com/thisiswisy/v0rtex-injector/files/1596398/app.docx)

**Comment by 211this** [comment]
Has sticktron all over crash reports

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by thisiswisy** [comment]
With beta 7 you can only use Cydia while the injector app is open. If you respring or quit injector you cannot use Cydia
