### ISSUE TITLE
Apple Mach-0 Linker Error

### ISSUE THREAD

**Issue by ryannairj** [thisiswisy/v0rtex-injector#64]
Getting 6 errors! Can't compile without fix. Anyone have a solution?

Undefined symbols for architecture x86_64:
  "_numhash", referenced from:
      _patch_amfi in amfi.o
  "_allhash", referenced from:
      _patch_amfi in amfi.o
  "_grab_hashes", referenced from:
      _patch_amfi in amfi.o
  "_allkern", referenced from:
      _patch_amfi in amfi.o
  "_amfitab", referenced from:
      _patch_amfi in amfi.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by thisiswisy** [comment]
Select your device not the simulator

**Comment by ryannairj** [comment]
Thanks a lot!
